#!/bin/bash 

echo 'input file name '
read var
echo 'input Description'
read des
echo ' input prototype'
read pro

echo -e '#include <stdlib.h>\n''#include <time.h>\n''#include <stdio.h>\n''#include "main.h"\n' > ${var}
echo '/**
*'${des}'
*/
'${pro}'
{

return (0);
}' >> ${var}
chmod u+x ${var}
vi ${var}
